image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test

build_model:
  stage: build
  script:
    - cd RobotokModel
    - dotnet build RobotokModel.csproj

build_view:
  stage: build
  tags: [windows]
  image: mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2019
  script:
    - dotnet build Robotok.sln

test_model:
  stage: test
  script:
    - dotnet test TestModel





